CREATE TABLE "WINESAMPLE" (
  "ID" BIGINT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  "VINTNERFIRSTNAME" VARCHAR(20),
  "VINTNERLASTNAME" VARCHAR(30),
  "VARIETY" VARCHAR(40),
  "COLOR" VARCHAR(6),
  "CHARACTER_" VARCHAR(4),
  "YEAR_" INT
);

CREATE TABLE "WineTastingSession" (
  "ID" BIGINT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  "place" VARCHAR(255),
  "date" DATE
);

CREATE TABLE "WineTasting" (
  "ID" BIGINT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  "sessionId" BIGINT NOT NULL, --REFERENCES WineTastingSession (ID),
  "sampleId" BIGINT NOT NULL --REFERENCES WineSample (ID)
);