INSERT INTO WINESAMPLE (VINTNERFIRSTNAME, VINTNERLASTNAME, VARIETY, COLOR, CHARACTER_, YEAR_)
VALUES('Lukáš','Tomovič','Rizling vlašský','WHITE','KAB','2014');
INSERT INTO WINESAMPLE (VINTNERFIRSTNAME, VINTNERLASTNAME, VARIETY, COLOR, CHARACTER_, YEAR_)
VALUES('Peter','Malý','Chardonnay','WHITE','VZH','2015');
INSERT INTO WINESAMPLE (VINTNERFIRSTNAME, VINTNERLASTNAME, VARIETY, COLOR, CHARACTER_, YEAR_)
VALUES('Milada','Kamenická','Alibernet','RED','NZ','2013');
INSERT INTO WINESAMPLE (VINTNERFIRSTNAME, VINTNERLASTNAME, VARIETY, COLOR, CHARACTER_, YEAR_)
VALUES('Maroš','Gofranko','Zweigeltrebe','ROSE','AKO','2012');
INSERT INTO WINESAMPLE (VINTNERFIRSTNAME, VINTNERLASTNAME, VARIETY, COLOR, CHARACTER_, YEAR_)
VALUES('Patrik','Friger','Frankovka modrá','RED','BV','2012');
INSERT INTO WINESAMPLE (VINTNERFIRSTNAME, VINTNERLASTNAME, VARIETY, COLOR, CHARACTER_, YEAR_)
VALUES('Ján','Recko','Svätovavrinecké','RED','BV','2015');
INSERT INTO WINESAMPLE (VINTNERFIRSTNAME, VINTNERLASTNAME, VARIETY, COLOR, CHARACTER_, YEAR_)
VALUES('Peter','Pekarčík','Irsai oliver','WHITE','HV','2011');
INSERT INTO WINESAMPLE (VINTNERFIRSTNAME, VINTNERLASTNAME, VARIETY, COLOR, CHARACTER_, YEAR_)
VALUES('Jozef','Mrkvička','Tramín červený','WHITE','LV','2014');
INSERT INTO WINESAMPLE (VINTNERFIRSTNAME, VINTNERLASTNAME, VARIETY, COLOR, CHARACTER_, YEAR_)
VALUES('Tomáš','Hlinený','Cabernet Sauvignon','RED','VZH','2013');

