CREATE TABLE "WINESAMPLE" (
  "ID" BIGINT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  "VINTNERFIRSTNAME" VARCHAR(20),
  "VINTNERLASTNAME" VARCHAR(30),
  "VARIETY" VARCHAR(40),
  "COLOR" VARCHAR(6),
  "CHARACTER_" VARCHAR(4),
  "YEAR_" INT
);

CREATE TABLE "WINETASTINGSESSION" (
  "ID" BIGINT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  "PLACE" VARCHAR(255),
  "DATE" DATE
);

CREATE TABLE "WINETASTING" (
  "ID" BIGINT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  "SESSIONID" BIGINT NOT NULL REFERENCES WineTastingSession (ID),
  "SAMPLEID" BIGINT NOT NULL REFERENCES WineSample (ID),
  "RATING" BIGINT
);
